sudo: required
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# versions of java to test (for parsers)
before_install:
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer oracle-java8-set-default
# command to install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install pytest coverage pytest-timeout
  - pip install python-coveralls
  - pip install --upgrade coverage
  - pip install .
#  - python -c "import kindred; kindred.downloadCoreNLP()" # not used as initial dependencies tests will run this
# command to run tests
script:
  - java -version
  - coverage --version
  - coverage run --branch -m pytest -v --timeout=90 && coverage report -m
after_success:
  - coveralls
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
